apiVersion: v1
kind: Service
metadata:
  name: helloweb
  namespace: helloweb  # Replace with your desired namespace
spec:
  selector:
    app: helloweb  # Ensure your Pods have this label
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007  # Ensure this is within the NodePort range (default: 30000-32767)
  type: NodePort
